# Generated by Django 5.1.7 on 2025-03-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizziz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
