# Generated by Django 5.1.7 on 2025-03-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizziz', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
